apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-sign-in-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-sign-in
  template:
    metadata:
      labels:
        app: user-sign-in
    spec:
      containers:
      - name: user-sign-in
        image: user-sign-in:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: user-sign-in-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: user-sign-in
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 32000
